### ISSUE TITLE
Burp 1.7.30 - no longer detecting s3 buckets

### ISSUE THREAD

**Issue by random-robbie** [VirtueSecurity/aws-extender#11]
Hey guys,

Did the usual upgrade and the plugin does not appear to detect any s3 buckets?

This is on Mac and Windows.

Example after doing a active scan against these buckets.

[![Capture.png](https://s2.postimg.org/bi2814321/Capture.png)](https://postimg.org/image/d9v6w0met/)

It still is not flagging in the issues area.

Nothing on my machines have changed and the keys do work i am using.

it is the same with azure buckets etc.

Can you please test and confirm?

**Comment by random-robbie** [comment]
just to say i confirmed by downgrading to 1.7.29

**Comment by 0xSobky** [comment]
Hey @random-robbie,

I ran a quick test using Burp 1.7.30 on Windows 7 and can confirm that the extension is working properly.

To help us figure out what could be causing this for you, please go to "Extender > Extensions > Cloud Storage Tester > Errors" and let us know if there are any error messages logged there.

Thank you!

**Comment by random-robbie** [comment]
Hi,

On both the mac and the windows machine none of them had any errors in the extender.

I will try an upgrade to 1.7.30 again shortly and I will see if I still have the issue.

**Comment by 0xSobky** [comment]
@random-robbie, you might also need to reinstall the plugin after upgrading and see if this, somehow, fixes the issue for you.

**Comment by random-robbie** [comment]
i've tried this and it works sometimes but not all the time.

Closing till i can replicate it easily
