### ISSUE TITLE
False Positive: s3-us-west-1.amazonaws.com [Enhancement]

### ISSUE THREAD

**Issue by random-robbie** [VirtueSecurity/aws-extender#13]
[![Screen_Shot_2017-12-28_at_23.21.14.png](https://s18.postimg.org/5bq25401l/Screen_Shot_2017-12-28_at_23.21.14.png)](https://postimg.org/image/nraj2ie5x/)

as you can see in the screen shot it has detected "s3-us-west-1.amazonaws.com" as the bucket.

it might be worth adding a blacklist to saying stuff like this isn't a bucket.

**Comment by 0xSobky** [comment]
Hi @random-robbie,

Thanks for reporting this, but "s3-us-west-1.amazonaws.com" is actually an existing bucket (http://s3-us-west-1.amazonaws.com.s3.amazonaws.com/).

Therefore, we'll be closing this issue. Please continue to report any other issues you encounter.
