### ISSUE TITLE
GS (Access/Secret) Keys Required

### ISSUE THREAD

**Issue by The1ntern** [VirtueSecurity/aws-extender#21]
Hi,

I am curious as to why the Google keys are required to be entered if I only need to test s3 buckets. Please let me know if I am missing something.

Thanks.

**Comment by 0xSobky** [comment]
I have added a [note](https://github.com/VirtueSecurity/aws-extender/commit/3029dd26bd7bdf7f4148e1e92adf9f8c547cafbe) to clear any confusion. GS keys are only required for authenticated GS tests. Sorry if that wasn't clear enough.
